block.block.*.third_party.block_breakpoint:
  type: mapping
  label: 'Block Breakpoint third party settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable the Block Breakpoint functionality'
    breakpoint_group:
      type: string
      label: 'The breakpoint group'
    breakpoints:
      type: sequence
      label: 'The breakpoints'
      sequence:
        type: mapping
        label: 'Breakpoint'
        mapping:
          breakpoint_id:
            type: string
            label: 'Breakpoint ID'
